// Turns data/players.json into supabase/seed_players.sql.
//   node scripts/build-players.mjs
// Re-run any time you edit the pool, then paste the SQL into Supabase.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// 2026 regular-season bye weeks (nfl.com, May 2026 schedule release).
export const BYE_WEEKS = {
  CAR: 5,  KC: 5,
  CIN: 6,  DET: 6,  MIA: 6,  MIN: 6,
  BUF: 7,  JAX: 7,  LAC: 7,  WAS: 7,
  HOU: 8,  NO: 8,   NYG: 8,  SF: 8,
  PIT: 9,  TEN: 9,
  CHI: 10, DEN: 10, PHI: 10, TB: 10,
  ATL: 11, CLE: 11, GB: 11,  LAR: 11, NE: 11, SEA: 11,
  BAL: 13, IND: 13, LV: 13,  NYJ: 13,
  ARI: 14, DAL: 14,
};

const slug = (name) =>
  name
    .toLowerCase()
    .replace(/[.'’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const { players } = JSON.parse(readFileSync(join(root, "data/players.json"), "utf8"));

const posCount = {};
const rows = players.map(([name, position, nfl_team], i) => {
  posCount[position] = (posCount[position] || 0) + 1;
  return {
    id: slug(name),
    name,
    position,
    nfl_team,
    bye_week: BYE_WEEKS[nfl_team] ?? null,
    rank: i + 1,
    adp: i + 1,
    pos_rank: `${position}${posCount[position]}`,
  };
});

const ids = new Set();
for (const r of rows) {
  if (ids.has(r.id)) throw new Error(`Duplicate player id: ${r.id} (${r.name})`);
  if (!r.bye_week) console.warn(`No bye week mapped for ${r.nfl_team} (${r.name})`);
  ids.add(r.id);
}

const q = (v) => (v === null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null ? "null" : String(v));

const sql = `-- Generated by scripts/build-players.mjs — do not edit by hand.
-- ${rows.length} players, 2026 bye weeks.
insert into public.nfl_players (id, name, position, nfl_team, bye_week, rank, adp, pos_rank) values
${rows
  .map(
    (r) =>
      `  (${q(r.id)}, ${q(r.name)}, ${q(r.position)}, ${q(r.nfl_team)}, ${n(r.bye_week)}, ${n(
        r.rank
      )}, ${n(r.adp)}, ${q(r.pos_rank)})`
  )
  .join(",\n")}
on conflict (id) do update set
  name = excluded.name, position = excluded.position, nfl_team = excluded.nfl_team,
  bye_week = excluded.bye_week, rank = excluded.rank, adp = excluded.adp,
  pos_rank = excluded.pos_rank;
`;

writeFileSync(join(root, "supabase/seed_players.sql"), sql);
console.log(`Wrote supabase/seed_players.sql — ${rows.length} players`);
